/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#ffb95f",
        "surface-container-highest": "#d3e4fe",
        "surface": "#f8f9ff",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#001a42",
        "surface-bright": "#f8f9ff",
        "inverse-primary": "#bcc7de",
        "outline": "#75777d",
        "on-primary-fixed-variant": "#3c475a",
        "error-container": "#ffdad6",
        "primary-fixed-dim": "#bcc7de",
        "primary": "#091426",
        "surface-container-low": "#eff4ff",
        "primary-container": "#1e293b",
        "secondary-fixed": "#d8e2ff",
        "primary-fixed": "#d8e3fb",
        "on-tertiary-fixed": "#2a1700",
        "on-secondary-fixed-variant": "#004395",
        "inverse-on-surface": "#eaf1ff",
        "background": "#f8f9ff",
        "on-primary-fixed": "#111c2d",
        "outline-variant": "#c5c6cd",
        "on-secondary": "#ffffff",
        "on-primary-container": "#8590a6",
        "tertiary-fixed": "#ffddb8",
        "on-tertiary": "#ffffff",
        "surface-tint": "#545f73",
        "error": "#ba1a1a",
        "surface-variant": "#d3e4fe",
        "on-secondary-container": "#fefcff",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#c88000",
        "on-surface": "#0b1c30",
        "secondary-fixed-dim": "#adc6ff",
        "on-surface-variant": "#45474c",
        "tertiary-container": "#3c2300",
        "secondary-container": "#2170e4",
        "inverse-surface": "#213145",
        "surface-dim": "#cbdbf5",
        "surface-container": "#e5eeff",
        "on-error": "#ffffff",
        "secondary": "#0058be",
        "surface-container-lowest": "#ffffff",
        "tertiary": "#201100"
      },
      fontFamily: {
        inter: ['Inter', 'sans-serif'],
      }
    },
  },
  plugins: [],
}
